### ISSUE TITLE
Error running exchange_with_ipc.py after generating blocks_rpc.json

### ISSUE THREAD

**Issue by jonjet** [medvedev1088/ethereum-etl#2]
After generating blocks_rpc.json, the following commmand exchange_with_ipc.py resulted in error.

python exchange_with_ipc.py --ipc-path=~/.local/share/io.parity.ethereum/jsonrpc.ipc --input=blocks_rpc.json --output=blocks_rpc_output.json
Traceback (most recent call last):
  File "exchange_with_ipc.py", line 20, in <module>
    response = socket_exchange(args.ipc_path, ''.join(line_batch), args.ipc_timeout)
  File "/home/user/ethereum-etl/ethereumetl/socket_utils.py", line 13, in socket_exchange
    sock.connect(socket_path)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by medvedev1088** [comment]
Thank you for reporting this issue. 

Try using `--ipc-path=$HOME/.local/share/io.parity.ethereum/jsonrpc.ipc` - looks like the ~ is not expanded by the shell as it's in the middle of the string. I will update README also.

However, parity is not supported by this tool at this point. The reason is geth and parity ipc work in a slightly different way as I found out:
- geth ipc will output an empty string at the end of the response so it's easy to determine when the data has been received completely 
- parity outputs empty strings even if it didn't finish outputting the response. 

The way it's handled in web3py, for example, is it will try to parse json after every `recv` and if a JSONDecodeError happened this means that the response is not full yet and it will continue to wait for the remainder of the response https://github.com/ethereum/web3.py/blob/master/web3/providers/ipc.py#L175 Parsing JSON adds a lot of overhead that's why I don't use web3py and wrote a custom socket handling.

web3py also doesn't support batch requests for now https://github.com/ethereum/web3.py/issues/832

I have a few TODOs for this project:
1. Unit tests
2. Send batch requests http://www.jsonrpc.org/specification#batch.
3. Support Parity
4. Add HTTPProvider
5. Error handling and logging

Any help would be appreciated.

**Comment by medvedev1088** [comment]
Thank you for the help!

I haven't done much programming in Python myself, most of my experience is Java/Kotlin. For unit testing I think we can use https://docs.pytest.org. It's the same tool that web3.py uses https://github.com/ethereum/web3.py. I suspect they already apply all the best practices so we could borrow configs, structure, workflows from there. 

A good start can be `ethereumetl.service.EthErc20Processor.filter_transfer_from_receipt_log`. The tests should give it test logs and check that the result is correct.

Btw, I have a business idea: SaaS solution for analysts and developers - "SQL for Blockchain". 
- Simple web console for running SQLs
- Built on top of AWS - cost efficient
- Users pay per query
- Can provide access to raw CSV data if needed
- Supports Ethereum at first, later Bitcoin and other blockchains can be added
- Internal transactions will be supported

If you know any businessmen, project managers, developers, including yourself, who might be interested to join, or if you have any ideas please let me know evge.medvedev@gmail.com.

**Comment by medvedev1088** [comment]
@jonjet I added support for Parity. Please help test when you have time.
